name: Release Bot

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm run install:ci

#      - name: Build Early Access
#        if: github.event.release.prerelease
#        run: npm run build:ea

#      - name: Build Production
#        if: !github.event.release.prerelease
#        run: npm run build:prod
