name: Release Bot

#on:
#  release:
#    types:
#      - published

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
            
      - name: Install dependencies
        run: npm run install:ci

#      - name: Build Early Access
#        if: github.event.release.prerelease
#        run: npm run build:ea

#      - name: Build Production
#        if: !github.event.release.prerelease
#        run: npm run build:prod
